version: '3.1'
services:
  servidor-wildfly:
    container_name: wildflycristina
    image: wildflycristina
    ports:
      - 8080:8080
      - 9990:9990
    restart: always
    command: ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]


  